#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="icoFoam"

mkdir 0
\cp -f 0_org/* 0/

runApplication potentialFoam
pyFoamPlotRunner.py --hardcopy --progress $application

#pyFoamPlotWatcher.py PyFoamRunner.$application.logfile --with-all
