#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="icoIbFoam"

blockMesh
\cp save/boundary constant/polyMesh/

mkdir 0
\cp -f 0_org/* 0/

runApplication potentialIbFoam
pyFoamPlotRunner.py --hardcopy --progress $application

#pyFoamPlotWatcher.py PyFoamRunner.$application.logfile --with-all
