#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
(cd refineSphereMesh; cleanApplication)

\rm -rf 0

pyFoamClearCase.py --remove-analyzed /home/ask/OpenFOAM/ask-3.2/run/tutorials/immersedBoundary/validation/stationary_sphere/sphereInChannel_3

#\rm -rf constant/polyMesh
